name: C/C++ CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install GCC11, pCap, Boost, wxWidgets
      run: sudo make prereq
    - name: make
      run: GTK_SUFFIX=3 make 2>&1 | tee build_log.txt
    - uses: actions/upload-artifact@v2
      with:
        name: build_log.txt
        path: build_log.txt
    - name: Install and run cppcheck
      run: sudo make prereq_cppcheck; make cppcheck
    - uses: actions/upload-artifact@v2
      with:
        name: cppcheck_html
        path: dir_cppcheck_html/
    - name: Check binary file
      run: ls -alh dynamo; file dynamo; readelf -a dynamo | grep NEEDED; ldd dynamo
