name: linux_cppcheck

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python Pygments
      run: sudo apt update; sudo apt install -y python-pygments
    - name: Run cppcheck
      run: ./3rdparty/cppcheck/cppcheck --cppcheck-build-dir=./dir_cppcheck_work/ --inline-suppr --force --xml -v --std=c++20 --enable=all '--suppress=*:/usr/include/*' precompiler.cpp
    - name: Run cppcheck-htmlreport
      run: ./3rdparty/cppcheck/cppcheck-htmlreport --file=err.xml --report-dir=./dir_cppcheck_html/ --source-dir=./
    - uses: actions/upload-artifact@v2
      with:
        name: cppcheck_html
        path: dir_cppcheck_html/
