name: linux_intel

on:
  push:
    branches: [notemp]
  pull_request:
    branches: [notemp]
jobs:
  build_intel_champ_fparser:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash --noprofile --norc {0}
    steps:
    - uses: actions/checkout@v2
    - name: setup repo
      run: |
        wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null; \
        echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list; \
        sudo apt update
    - name: install
      run: |
        sudo apt install -y intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-2022.1.0
    - name: Compile pre-compiler
      run: |
        source /opt/intel/oneapi/setvars.sh; \
        printenv >> $GITHUB_ENV; \
        icpc -o precompiler ./precompiler.cpp -std=c++17
    - name: Test pre-compiler
      run: |
        icpc -E -P sample_lasers.cpp | ./precompiler > final_lasers.cpp; \
        icpc -o bin_lasers final_lasers.cpp -std=c++17; \
        icpc -E -P sample_simple.cpp | ./precompiler > final_simple.cpp; \
        icpc -o bin_simple final_simple.cpp -std=c++17
