name: linux_g++

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install version 11 of GNU compiler suite
      run: sudo apt update; sudo apt install -y gcc-11 g++-11; sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11; uname -a; g++ --version | grep g++
    - uses: actions/checkout@v2
    - name: Compiler pre-compiler
      run: g++ -o precompiler precompiler.cpp -std=c++20 -fdump-rtl-expand -DNDEBUG -O3 -s > build_log.txt 2>&1
    - uses: actions/upload-artifact@v2
      with:
        name: build_log.txt
        path: build_log.txt
    - name: Check binary file
      run: ls -alh precompiler; file precompiler; readelf -a precompiler | grep NEEDED; ldd precompiler
    - name: create lasers translation unit
      run: g++ -std=c++20 -E -P sample_lasers.cpp | ./precompiler > trans_lasers.cpp
    - name: create simple translation unit
      run: g++ -std=c++20 -E -P sample_simple.cpp | ./precompiler > trans_simple.cpp
    - name: build binary for lasers sample
      run: g++ -o bin_lasers trans_lasers.cpp -std=c++20
    - name: build binary for simple sample
      run: g++ -o bin_simple trans_simple.cpp -std=c++20
    - name: build the separate program for comparing text files
      run: g++ -o comparetxt comparetxt.cpp -std=c++20
    - name: compare expected output for lasers sample
      run:  ./bin_lasers | ./comparetxt expected_output_lasers.txt
    - name: compare expected output for simple sample
      run:  ./bin_simple | ./comparetxt expected_output_simple.txt
    - name: Install egypt and thomas_egypt for graphical graph of function calls
      run: echo Nothing || (cd 3rdparty/egypt/; sudo ./setup_thomas_egypt.sh)
    - name: Run thomas_egypt to generate main_as_root.png
      run: echo Nothing || (cd 3rdparty/egypt/; ./thomas_egypt main ../../*expand*)
