name: microsoft

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    name: run on windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: compile
      run: cl precompiler.cpp /std:c++20
    - name: run
      run: echo frog | precompiler.exe
      shell: cmd
    - name: upload executable
      uses: actions/upload-artifact@v2
      with:
        name: precompiler_for_mswindows
        path: precompiler.exe
